# Generated by Django 5.0.2 on 2024-03-04 18:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("article", "0003_article_articlei_mage"),
    ]

    operations = [
        migrations.RenameField(
            model_name="article",
            old_name="articleİmage",
            new_name="articleImage",
        ),
    ]
