# Generated by Django 5.0.2 on 2024-03-09 10:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("article", "0005_comment"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="article",
            options={"ordering": ["-createdDate"]},
        ),
        migrations.AlterModelOptions(
            name="comment",
            options={"ordering": ["-comment_date"]},
        ),
    ]
